/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test
    public void testStoneOustsSisors() {
        assertEquals(new Stone(), new Stone().oust(new Scissors()));
    }

    @Test public void testStoneWasOustedByPaper() {
        assertEquals(new Paper(), new Stone().oust(new Paper()));
    }

    @Test
    public void testSisorsOustsPaper() {
        assertEquals(new Scissors(), new Scissors().oust(new Paper()));
    }

    @Test
    public void testSisorsWasOustedByStone() {
        assertEquals(new Stone(), new Scissors().oust(new Stone()));
    }

    @Test
    public void testPaperOustsStone() {
        assertEquals(new Paper(), new Paper().oust(new Stone()));
    }

    @Test
    public void testPaperWasOustedBySisors() {
        assertEquals(new Scissors(), new Paper().oust(new Scissors()));
    }
}
